server:
  host: 127.0.0.1
  port: 8888
mail:
  smtp:
    host: "smtp.163.com"
    port: "25"
    username: "gochat2025@163.com"
    auth_code: "AGb9N6LbhrJnsXc7"
db:
  mysql:
    dsn:  "root:root@tcp(127.0.0.1:3306)/chat?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpenConn: 10
    maxIdleConn: 10
jwt:
  secret: "gochat2025"
oauth:
  github:
    client_id: "Ov23liRJAg1oNDP6IWTA"
    client_secret: "141dd2cd95e0c3e3e7a7aa2f73ed297c1b348643"
    redirect_uri: "http://localhost:8080/oauth/github"
  wechat:
    app_id: "wx4f30218dee2d16fd"
    app_secret: "c073919f5ddeea6b64376548836e2a75"
    redirect_uri: "http://localhost:8080/oauth/wechat"